---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: centos7
    image: centos:centos7
    privileged: True  # systemd requirement
    # command: "/lib/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"  # systemd requirement
    devices:
      - "/dev/loop0:/dev/loop0"  # mounting ISO requirement
  - name: ubuntu18
    image: ubuntu:18.04
    privileged: True  # systemd requirement
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"  # systemd requirement
    devices:
      - "/dev/loop0:/dev/loop0"  # mounting ISO requirement
  - name: debian10
    image: debian:10-slim
    privileged: True  # systemd requirement
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"  # systemd requirement
    devices:
      - "/dev/loop0:/dev/loop0"  # mounting ISO requirement
provisioner:
  name: ansible
  log: True
  options:
    verbose: True
  lint:
    name: ansible-lint
    options:
      x:
        - 203
        - 305
verifier:
  name: testinfra
  lint:
    name: flake8
